[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
via_ir = false
optimizer = true
optimizer_runs = 999999
evm_version = "cancun"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  fraxtal = { key = "${API_KEY_FRAXTAL}" }
  base = { key = "${API_KEY_ETHERSCAN}" }
  sepolia = {key = "${API_KEY_ETHERSCAN}"}

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  fraxtal = "https://rpc.frax.com"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

[lint]
exclude_lints = ["screaming-snake-case-immutable"]


[invariant]
runs = 1024
depth = 32

