[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
via_ir = false
optimizer = true
optimizer_runs = 999999
evm_version = "cancun"

[lint]
exclude_lints = ["screaming-snake-case-immutable"]


[invariant]
runs = 1024
depth = 32

